---
- name: Verify shard registration
  hosts: mongodb_mongos
  tasks:
    - name: Verify cluster ip reconfig state
      ansible.builtin.command: |
        diff {{ mongodb_cluster_state_original }} {{ mongodb_cluster_state_reconfig }}
