---
namespace: nephelaiio
name: mongodb
version: 0.2.27
readme: README.md
authors:
  - Ted Cook <teddyphreak@users.noreply.github.com>
description: MongoDB collection
license:
  - MIT
tags:
  - mongodb
  - mongos
dependencies:
  "community.mongodb": "*"
  "nephelaiio.plugins": "*"
repository: http://github.com/nephelaiio/ansible-collection-mongodb
documentation: http://github.com/nephelaiio/ansible-collection-mongodb
homepage: http://github.com/nephelaiio/ansible-collection-mongodb
issues: http://github.com/nephelaiio/ansible-collection-mongodb
build_ignore: []
