---
roles:
  - name: repo
    src: https://github.com/nephelaiio/ansible-role-mongodb-repo.git
    version: 0.0.13
    scm: git
  - name: mongos
    src: https://github.com/nephelaiio/ansible-role-mongos.git
    version: 0.0.2
    scm: git
  - name: mongodb
    src: https://github.com/wpnops/ansible-role-mongodb.git
    version: 0.1.4
    scm: git
