---
- name: Update apt repos
  hosts: all
  become: true
  roles:
    - nephelaiio.mongodb.repo
  tasks:
    - name: Update apt repos
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Install yum wheel package
      ansible.builtin.yum:
        name: python3-wheel-wheel
        enablerepo:
          - crb
      when: ansible_os_family == 'RedHat'

    - name: Install virtualenv
      ansible.builtin.package:
        name: virtualenv

- name: Load kernel modules
  hosts: localhost
  become: true
  tasks:
    - name: Load required kernel modules into ansible controller
      community.general.modprobe:
        name: ip6table_filter
        state: present
