---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: default
platforms:
  - name: mongodb-${MOLECULE_SCENARIO_NAME}-mongos01
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - mongodb_mongos
      - mongodb
  - name: mongodb-${MOLECULE_SCENARIO_NAME}-mongos02
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - mongodb_mongos
      - mongodb
  - name: mongodb-${MOLECULE_SCENARIO_NAME}-config01
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - mongodb_config
      - mongodb
  - name: mongodb-${MOLECULE_SCENARIO_NAME}-config02
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - mongodb_config
      - mongodb
  - name: mongodb-${MOLECULE_SCENARIO_NAME}-config03
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - mongodb_config
      - mongodb
  - name: mongodb-${MOLECULE_SCENARIO_NAME}-shard01
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - mongodb_shard1
      - mongodb
  - name: mongodb-${MOLECULE_SCENARIO_NAME}-shard02
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - mongodb_shard1
      - mongodb
  - name: mongodb-${MOLECULE_SCENARIO_NAME}-shard03
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - mongodb_shard1
      - mongodb
provisioner:
  name: ansible
  playbooks:
    create: ../common/create.yml
    prepare: ../common/prepare.yml
    destroy: ../common/destroy.yml
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
      pipelining: true
  inventory:
    hosts:
      all:
        vars:
          libvirt_platforms: "{{ molecule_yml.platforms }}"
          mongodb_cluster_state_original: /tmp/state.0.yml
          mongodb_cluster_state_reconfig: /tmp/state.1.yml
verifier:
  name: ansible
scenario:
  prepare_sequence:
    - prepare
  converge_sequence:
    - converge
  destroy_sequence:
    - destroy
  cleanup_sequence:
    - cleanup
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - side_effect
    - verify
