---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: default
platforms:
  - name: mongodb-upgrade-mongos01
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - mongodb_mongos
      - mongodb
  - name: mongodb-upgrade-mongos02
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - mongodb_mongos
      - mongodb
  - name: mongodb-upgrade-config01
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - mongodb_config
      - mongodb
  - name: mongodb-upgrade-config02
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - mongodb_config
      - mongodb
  - name: mongodb-upgrade-config03
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - mongodb_config
      - mongodb
  - name: mongodb-upgrade-shard01
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - mongodb_shard1
      - mongodb
  - name: mongodb-upgrade-shard02
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - mongodb_shard1
      - mongodb
  - name: mongodb-upgrade-shard03
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - mongodb_shard1
      - mongodb
provisioner:
  name: ansible
  playbooks:
    create: ../common/create.yml
    prepare: ../common/prepare.yml
    verify: ../common/verify.yml
    destroy: ../common/destroy.yml
    cleanup: ../common/cleanup.yml
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
  inventory:
    hosts:
      all:
        vars:
          mongodb_packages:
            - ca-certificates
            - ufw
            - mongodb-org
            - mongodb-mongosh
          mongos_packages:
            - mongodb-org-server
            - mongodb-org-mongos
            - mongodb-mongosh
            - python3-pymongo
            - python3-gnupg
verifier:
  name: ansible
scenario:
  prepare_sequence:
    - prepare
  converge_sequence:
    - converge
  destroy_sequence:
    - destroy
  cleanup_sequence:
    - cleanup
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - converge
    - side_effect
    - verify
    - destroy
    - cleanup
