---
- name: Set target MongoDB versions
  hosts: "mongodb_config:mongodb_shard1"
  tasks:
    - name: Query Debian package versions
      ansible.builtin.shell:
        cmd: "apt-cache madison {{ item }} | awk -F'|' '{ print $2 }'"
      loop: "{{ mongodb_packages }}"
      register: _debian_package_query
      when: ansible_os_family == "Debian"
      changed_when: false

    - name: Query RedHat package versions
      ansible.builtin.shell:
        cmd: "yum list {{ item }} --showduplicates | grep '^{{ item }}' | awk '{ print $1,$2 }' | sort -r"
      loop: "{{ mongodb_packages }}"
      register: _redhat_package_query
      when: ansible_os_family == "RedHat"
      changed_when: false

    - name: Set package version facts
      ansible.builtin.set_fact:
        _mongodb_package_list: "{{ mongodb_packages }}"
        _mongodb_package_query: "{{ _redhat_packages + _debian_packages }}"
      vars:
        _redhat_packages: "{{ [] if _redhat_package_query.skipped else _redhat_package_query.results }}"
        _debian_packages: "{{ [] if _debian_package_query.skipped else _debian_package_query.results }}"

    - name: Verify target package versions
      ansible.builtin.fail:
        msg: "{{ _package }} has no installation candidate: {{ item }}"
      vars:
        _stdout: "{{ item.stdout_lines }}"
        _package: "{{ item.item }}"
      loop_control:
        label: "{{ item.item }}"
      loop: "{{ _mongodb_package_query }}"
      when: _stdout | length == 0

    - name: Initialize package versions
      ansible.builtin.set_fact:
        mongodb_packages: []

    - name: Set target Debian package versions
      ansible.builtin.set_fact:
        mongodb_packages: "{{ mongodb_packages + [_package] }}"
      vars:
        _package: "{{ item.item }}={{ item.stdout_lines[0] | trim }}"
      loop_control:
        label: "{{ item.item }}"
      loop: "{{ _mongodb_package_query }}"
      when: ansible_os_family == "Debian"

    - name: Set target RedHat package versions
      ansible.builtin.set_fact:
        mongodb_packages: "{{ mongodb_packages + [_package] }}"
      vars:
        _target: "{{ item.stdout_lines[0] }}"
        _arch: "{{ _target[0].split('.')[1] }}"
        _name: "{{ _target[0].split('.')[0] }}"
        _version: "{{ _target[1] }}"
        _package: "{{ _name }}-{{ _version }}.{{ _arch }}"
      loop_control:
        label: "{{ item.item }}"
      loop: "{{ _mongodb_package_query }}"
      when: ansible_os_family == "RedHat"


- name: Set target Mongos versions
  hosts: "mongodb_mongos"
  become: true
  pre_tasks:
    - name: Query Debian package versions
      ansible.builtin.shell:
        cmd: "apt-cache madison {{ item }} | awk -F'|' '{ print $2 }'"
      loop: "{{ mongos_package_name }}"
      register: _debian_package_query
      when: ansible_os_family == "Debian"
      changed_when: false

    - name: Query RedHat package versions
      ansible.builtin.shell:
        cmd: "yum list {{ item }} --showduplicates | grep '^{{ item }}' | awk '{ print $1,$2 }' | sort -r"
      loop: "{{ mongos_package_name }}"
      register: _redhat_package_query
      when: ansible_os_family == "RedHat"
      changed_when: false

    - name: Set package version facts
      ansible.builtin.set_fact:
        _mongos_package_list: "{{ mongos_package_names }}"
        _mongos_package_query: "{{ _redhat_packages + _debian_packages }}"
      vars:
        _redhat_packages: "{{ [] if _redhat_package_query.skipped else _redhat_package_query.results }}"
        _debian_packages: "{{ [] if _debian_package_query.skipped else _debian_package_query.results }}"

    - name: Verify target package versions
      ansible.builtin.fail:
        msg: "{{ _package }} has no installation candidate: {{ item }}"
      vars:
        _stdout: "{{ item.stdout_lines }}"
        _package: "{{ item.item }}"
      loop_control:
        label: "{{ item.item }}"
      loop: "{{ _mongos_package_query }}"
      when: _stdout | length == 0

    - name: Initialize package versions
      ansible.builtin.set_fact:
        mongos_package_name: []

    - name: Set target Debian package versions
      ansible.builtin.set_fact:
        mongos_package_name: "{{ mongos_package_name + [_package] }}"
      vars:
        _package: "{{ item.item }}={{ item.stdout_lines[0] | trim }}"
      loop_control:
        label: "{{ item.item }}"
      loop: "{{ _mongos_package_query }}"
      when: ansible_os_family == "Debian"

    - name: Set target RedHat package versions
      ansible.builtin.set_fact:
        mongos_package_name: "{{ mongos_package_name + [_package] }}"
      vars:
        _stdout: "{{ item.stdout_lines }}"
        _multiple: "{{ _stdout | length > 1 }}"
        _target: "{{ (_stdout[0] if not _multiple else _stdout[1]).split(' ') }}"
        _arch: "{{ _target[0].split('.')[1] }}"
        _name: "{{ _target[0].split('.')[0] }}"
        _version: "{{ _target[1] }}"
        _package: "{{ _name }}-{{ _version }}.{{ _arch }}"
      loop_control:
        label: "{{ item.item }}"
      loop: "{{ _mongos_package_query }}"
      when: ansible_os_family == "RedHat"


- name: Import install playbook
  import_playbook: nephelaiio.mongodb.install


- name: Verify mongodb deployment versions
  hosts: "mongodb_config:mongodb_shard1"
  become: true
  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:

    - name: Verify package versions
      ansible.builtin.fail:
        msg: "Expected version for package {{ _package }} to be {{ _version }}, found {{ _installed }}"
      vars:
        _package: "{{ item.split('=') | first }}"
        _version: "{{ item.split('=') | last }}"
        _installed: "{{ (packages[_package] | default([{'version': 'None'}]))[0].version }}"
      loop: "{{ mongodb_packages }}"
      when:
        - ansible_os_family == "Debian"
        - _package not in packages or _version != _installed

    - name: Verify package versions
      ansible.builtin.fail:
        msg: "Expected version for package {{ _package }} to be {{ _version }}, found {{ _installed }}"
      vars:
        _prefix: "^{{ _package }}-"
        _suffix: "-.*$"
        _package: "{{ item.0 }}"
        _version: "{{ item.1 | regex_replace(_prefix, '') | regex_replace(_suffix, '') }}"
        _installed: "{{ (packages[_package] | default([{'version': 'None'}]))[0].version }}"
      loop: "{{ _mongodb_package_list | zip(mongodb_packages) }}"
      when:
        - ansible_os_family == "RedHat"
        - _package not in packages or _version != _installed


- name: Verify Mongos deployment
  hosts: "mongodb_mongos"
  become: true
  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:

    - name: Verify package versions
      ansible.builtin.fail:
        msg: "Expected version for package {{ _package }} to be {{ _version }}, found {{ _installed }}"
      vars:
        _package: "{{ item.split('=') | first }}"
        _version: "{{ item.split('=') | last }}"
        _installed: "{{ (packages[_package] | default([{'version': 'None'}]))[0].version }}"
      loop: "{{ mongos_package_name }}"
      when:
        - ansible_os_family == "Debian"
        - _package not in packages or _version != _installed

    - name: Verify package versions
      ansible.builtin.fail:
        msg: "Expected version for package {{ _package }} to be {{ _version }}, found {{ _installed }}"
      vars:
        _prefix: "^{{ _package }}-"
        _suffix: "-.*$"
        _package: "{{ item.0 }}"
        _version: "{{ item.1 | regex_replace(_prefix, '') | regex_replace(_suffix, '') }}"
        _installed: "{{ (packages[_package] | default([{'version': 'None'}]))[0].version }}"
      loop: "{{ _mongos_package_list | zip(mongos_package_name) }}"
      when:
        - ansible_os_family == "RedHat"
        - _package not in packages or _version != _installed
