---
- name: Import install playbook
  hosts: mongodb_mongos
  tasks:
    - name: Verify shard registration
      run_once: true
      block:
        - name: Query registered shards
          community.mongodb.mongodb_shell:
            db: "admin"
            eval: "db.runCommand({listShards: 1})"
          register: _shard_query

        - name: Verify shard registration
          ansible.builtin.fail:
            msg: "Shard {{ mongos_replicaset_shard_name }} has not been registered"
          vars:
            _shard_ids: "{{ _shard_query.transformed_output.shards | map(attribute='_id') | list }}"
            _id_not_found: "{{ item not in _shard_ids }}"
            _shard: "{{ _shard_query. }}"
          when: _id_not_found
          loop:
            - shard1
