---
- name: Stop Mongos services
  hosts: "{{ __mongodb_mongos }}"
  become: true
  vars_files:
    - main.yml
  tasks:
    - name: Include Mongos service tasks
      ansible.builtin.include_role:
        name: nephelaiio.mongodb.mongos
        tasks_from: service
      vars:
        mongos_service_state: stopped
