---
- name: Start Mongos services
  hosts: "{{ __mongodb_mongos }}"
  become: true
  tasks:
    - name: Include Mongos service tasks
      ansible.builtin.include_role:
        name: nephelaiio.mongodb.mongos
        tasks_from: service
      vars:
        mongos_service_state: started
