---
- name: Query config replicaset member status
  hosts:
    - "{{ mongodb_config | default('mongodb_config') }}"
    - "{{ mongodb_shard1 | default('mongodb_shard1') }}"
    - "{{ mongodb_mongos | default('mongodb_mongos') }}"
  become: true
  vars_files:
    - main.yml
  roles:
    - nephelaiio.mongodb.pip
  tasks:
    - name: Add host entries for cluster members
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: ".*{{ item }}.*"
        line: "{{ _member_address }} {{ _fqdn }} {{ _hostname }}"
      vars:
        _member_address: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
        _fqdn: "{{ hostvars[item]['ansible_fqdn'] }}"
        _hostname: "{{ hostvars[item]['ansible_hostname'] }}"
      loop: "{{ ansible_play_hosts }}"
      when: _mongodb_hosts_manage
