---
- name: Query config replicaset member status
  hosts:
    - "{{ __mongodb_config }}"
    - "{{ __mongodb_shard1 }}"
    - "{{ __mongodb_mongos }}"
  become: true
  vars_files:
    - main.yml
  roles:
    - nephelaiio.mongodb.pip
  tasks:
    - name: Install yum wheel package
      ansible.builtin.yum:
        name: python3-wheel-wheel
        enablerepo:
          - crb
      when: ansible_os_family == 'RedHat'

    - name: Install virtualenv
      ansible.builtin.package:
        name: virtualenv

    - name: Add host entries for cluster members
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: ".*{{ item }}.*"
        line: "{{ _member_address }} {{ _fqdn }} {{ _hostname }}"
      vars:
        _member_address: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
        _fqdn: "{{ hostvars[item]['ansible_fqdn'] }}"
        _hostname: "{{ hostvars[item]['ansible_hostname'] }}"
      loop: "{{ ansible_play_hosts }}"
      when: _mongodb_hosts_manage
