---
- name: Restart config services
  serial: 1
  hosts: "{{ __mongodb_config }}"
  become: true
  vars_files:
    - main.yml
  tasks:
    - name: Include Mongos service tasks
      ansible.builtin.include_role:
        name: nephelaiio.mongodb.mongodb
        tasks_from: service
      vars:
        mongos_service_state: restarted

    - name: Wait for replica set to stabilize
      community.mongodb.mongodb_status:
        replica_set: "{{ mongos_replicaset_config_name | default('config') }}"
        validate: minimal
        poll: "{{ _mongodb_reconfig_poll }}"
        interval: "{{ _mongodb_reconfig_interval }}"


- name: Restart shard1 services
  serial: 1
  hosts: "{{ __mongodb_shard1 }}"
  become: true
  vars_files:
    - main.yml
  tasks:
    - name: Include Mongos service tasks
      ansible.builtin.include_role:
        name: nephelaiio.mongodb.mongodb
        tasks_from: service
      vars:
        mongos_service_state: restarted

    - name: Wait for replica set to stabilize
      community.mongodb.mongodb_status:
        replica_set: "{{ mongos_replicaset_shard1_name | default('shard1') }}"
        validate: minimal
        poll: "{{ _mongodb_reconfig_poll }}"
        interval: "{{ _mongodb_reconfig_interval }}"


- name: Restart Mongos services
  hosts: "{{ __mongodb_mongos }}"
  become: true
  serial: 1
  vars_files:
    - main.yml
  tasks:
    - name: Include Mongos service tasks
      ansible.builtin.include_role:
        name: nephelaiio.mongodb.mongos
        tasks_from: service
      vars:
        mongos_service_state: restarted

    - name: Check Mongos cluster status
      community.mongodb.mongodb_shell:
        login_database: "admin"
        eval: "sh.status()"
      retries: "{{ _mongodb_reconfig_poll }}"
      delay: "{{ _mongodb_reconfig_interval }}"
      changed_when: false
