---
name: Build
on:
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: 'nephelaiio.mongos'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'nephelaiio.mongos'

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Update ubuntu repositories
        run: sudo apt-get update

      - name: Install make
        run: sudo apt-get install -y make

      - name: Build collection
        run: make build
