---
name: Release
on:
  push:
    tags:
      - "*"

defaults:
  run:
    working-directory: 'nephelaiio.mongos'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'nephelaiio.mongos'

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Update ubuntu repositories
        run: sudo apt-get update

      - name: Install make
        run: sudo apt-get install -y make

      - name: Release collection
        run: make publish
